### ISSUE TITLE
Support Aliucord-RN.

### ISSUE THREAD

**Issue by GittyMac** [catppuccin/aliucord#3]
The React Native version of Aliucord added a built-in theme plugin. It uses a new JSON layout that appears to be undocumented.

**Comment by isabelincorp** [comment]
I'll take a look at it when I can, hopefully they can get things documented!

**Comment by RoootTheFox** [comment]
You can just use [catppuccin/enmity](https://github.com/catppuccin/enmity) for Aliucord RN
beware that both Aliucord and Enmity seem a little unstable rn as discord is pushing out a lot of breaking changes (latest alpha has unthemed parts, latest discord stable w/ enmity on iOS does as well)

**Comment by lrxyab** [comment]
Should I mark it as non planned because I think aliucordRN is scrapped now?

**Comment by isabelincorp** [comment]
Yes, please do!
