### ISSUE TITLE
Support all flavour-accent combinations

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/aliucord#8]
As expressed by @myumichi, this port should be extended to support all of the Catppuccin accents.

[Whiskers](https://github.com/catppuccin/whiskers), our port creation helper tool, may be able to help with this generation (I believe @uncenter was interested in trying to replicate the 32 bit integer output from the latest version.)

**Comment by uncenter** [comment]
Would be happy to help! I have a template going already but we might need to implement some custom logic in Whiskers to support Aliucord's odd color format. It [isn't complicated in Rust](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5672c2eac07cd2f5aa1baab5cec1f0b7) but it is annoying to do in Tera logic.
